version: '3.8'

services:

  # MongoDB
  # https://hub.docker.com/_/mongo
  mongo:
    image: mongo:4-bionic
    container_name: mongo
    hostname: mongo-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - TZ=<TZ>
    expose:
      - '27017'
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-data:
    external: true
  mongo-config:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
