version: '3.8'

services:

  # Gitea
  # Image:
  # https://hub.docker.com/r/gitea/gitea
  # Docs:
  # https://docs.gitea.io/en-us/config-cheat-sheet/
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    hostname: gitea-server
    environment:
      # for nginx-proxy
      - VIRTUAL_HOST=gitea.<DOMAIN>
      - VIRTUAL_PORT=3000
      #SSL#- SSL_POLICY=Mozilla-Modern
      #NO_HSTS#- HSTS=off
      #SELF_SIGN#- SSL_POLICY=self-sign

      - TZ=<TZ>
    expose:
      #- '22'
      - '3000'
    volumes:
      - gitea-data:/data
      - ./volumes/conf:/data/gitea/conf
      # CA bundle
      #SELF_SIGN#- ../setup/self-sign-cert/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: unless-stopped
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - auth.<DOMAIN>:<LOCAL_IP>

volumes:
  gitea-data:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
