version: '3.8'

services:

  # pgAdmin
  # Image:
  # https://hub.docker.com/r/dpage/pgadmin4
  # Docs:
  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pga-server
    environment:
      - PGADMIN_DEFAULT_EMAIL=webmaster@<DOMAIN>
      - PGADMIN_DEFAULT_PASSWORD=Pa55w@rd
      - PGADMIN_DISABLE_POSTFIX=true

      # for nginx-proxy
      - VIRTUAL_HOST=pga.<DOMAIN>
      - VIRTUAL_PORT=80
      - NETWORK_ACCESS=internal

      - TZ=<TZ>
    expose:
      - '80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: unless-stopped
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgadmin-data:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
