version: '3.8'

services:

  # RabbitMQ
  # Image:
  # https://hub.docker.com/_/rabbitmq
  # Docs:
  # https://www.rabbitmq.com/configure.html#config-file
  # https://www.rabbitmq.com/configure.html#supported-environment-variables
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rmq-server
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      #- RABBITMQ_DEFAULT_VHOST=

      # for nginx-proxy
      - VIRTUAL_HOST=rmq.<DOMAIN>
      - VIRTUAL_PORT=15672
      - NETWORK_ACCESS=internal

      - TZ=<TZ>
    expose:
      - '5672'
      - '15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      #- ./mount/enabled_plugins:/etc/rabbitmq/enabled_plugins

      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: always
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rabbitmq-data:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
