version: '3.8'

services:

  # phpMyAdmin
  # https://hub.docker.com/_/phpmyadmin
  # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    hostname: pma-server
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=maria-server
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ABSOLUTE_URI=<PROTOCOLL>://pma.<DOMAIN>/

      # for nginx-proxy
      - VIRTUAL_HOST=pma.<DOMAIN>
      - VIRTUAL_PORT=80
      - NETWORK_ACCESS=internal

      - TZ=<TZ>
    expose:
      - '80'
    volumes:
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: unless-stopped
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
