version: '3.8'

services:

  # CodiMD
  # Image:
  # https://hub.docker.com/r/hackmdio/hackmd
  # Docs:
  # https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-docker-deployment
  # https://hackmd.io/s/codimd-configuration
  # Auth:
  # https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-auth-saml
  # https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-auth-saml-onelogin
  codimd:
    image: hackmdio/hackmd:latest
    container_name: codimd
    hostname: codimd-server
    environment:
      - CMD_DOMAIN=codimd.<DOMAIN>

      - CMD_USECDN=false
      - CMD_AUTO_VERSION_CHECK=false
      - CMD_ALLOW_ORIGIN=codimd.<DOMAIN>
      - CMD_DB_URL=postgres://root:root@pg-server:5432/codimd
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_DEFAULT_PERMISSION=private
      - CMD_ALLOW_PDF_EXPORT=true
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_ALLOW_EMAIL_REGISTER=false

      #- GROWI_URI=<PROTOCOL>://growi.<DOMAIN>
      - CMD_CSP_ENABLE=false

      - CMD_EMAIL=false
      - CMD_SAML_IDPSSOURL=<PROTOCOL>://auth.<DOMAIN>/auth/realms/<REALM>/protocol/saml/clients/codimd.<DOMAIN>
      - CMD_SAML_IDPCERT=/codimd/keycloak_relm.crt
      - CMD_SAML_ISSUER=app-codimd
      - CMD_SAML_IDENTIFIERFORMAT=urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
      #- CMD_SAML_GROUPATTRIBUTE=
      #- CMD_SAML_REQUIREDGROUPS=
      #- CMD_SAML_EXTERNALGROUPS=
      - CMD_SAML_ATTRIBUTE_ID=id
      - CMD_SAML_ATTRIBUTE_USERNAME=username
      - CMD_SAML_ATTRIBUTE_EMAIL=email

      #SSL#- CMD_PROTOCOL_USESSL=true
      #NO_SSL#- CMD_PROTOCOL_USESSL=false

      # for nginx-proxy
      - VIRTUAL_HOST=codimd.<DOMAIN>
      - VIRTUAL_PORT=3000
      #SSL#- SSL_POLICY=Mozilla-Modern
      #NO_HSTS#- HSTS=off
      #SELF_SIGN#- CERT_NAME=self-sign

      - TZ=<TZ>
    expose:
      - '3000'
    volumes:
      - codimd-uploads:/codimd/public/uploads
      - ./mount/keycloak_relm.crt:/codimd/keycloak_relm.crt:ro
      # Load GROWI Agent
      #- ./mount/head.ejs:/home/hackmd/app/public/views/codimd/head.ejs:ro
      #- ./mount/foot.ejs:/home/hackmd/app/public/views/codimd/foot.ejs:ro
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: unless-stopped
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - auth.<DOMAIN>:<LOCAL_IP>

volumes:
  codimd-uploads:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
