version: '3.8'


services:

  # Wiki.js
  # Image:
  # https://hub.docker.com/r/requarks/wiki
  # Docs:
  # https://docs.requarks.io/install/docker
  # https://docs.requarks.io/en/auth/saml
  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    hostname: wikijs-server
    environment:
      - DB_TYPE=postgres
      - DB_HOST=pg-server
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=wikijs
      #- DB_SSL=
      #- DB_SSL_CA=
      #- DB_PASS_FILE=
      #- DB_FILEPATH=

      #- SSL_ACTIVE=true
      #- LETSENCRYPT_DOMAIN=
      #- LETSENCRYPT_EMAIL=

      #- HA_ACTIVE=

      # for nginx-proxy
      - VIRTUAL_HOST=wikijs.<DOMAIN>
      - VIRTUAL_PORT=3000
      #SSL#- SSL_POLICY=Mozilla-Modern
      #NO_HSTS#- HSTS=off
      #SELF_SIGN#- CERT_NAME=self-sign

      - TZ=<TZ>
    expose:
      - '3000'
      #- '3443'
    volumes:
      - wikijs-content:/wiki/data/content

      # CA bundle
      #SELF_SIGN#- ../setup/self-sign-cert/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: unless-stopped
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - auth.<DOMAIN>:<LOCAL_IP>

volumes:
  wikijs-content:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
