docker volume create codimd-uploads
docker volume create elasticsearch-data
docker volume create gitea-data
docker volume create gitlab-data
docker volume create gitlab-logs
docker volume create gitlab-node_modules
docker volume create growi-data
docker volume create maria-data
docker volume create mattermost-client-plugins
docker volume create mattermost-config
docker volume create mattermost-data
docker volume create mattermost-indexes
docker volume create mattermost-logs
docker volume create mattermost-plugins
docker volume create mongo-config
docker volume create mongo-data
docker volume create mongo-repl-config
docker volume create mongo-repl-data
docker volume create nextcloud-main
docker volume create nextcloud-apps
docker volume create nextcloud-data
docker volume create penpot-data
docker volume create pgadmin-data
docker volume create portainer-data
docker volume create postgres-data
docker volume create proxy-dhparam
docker volume create rabbitmq-data
docker volume create redis-data
docker volume create redisinsight-data
docker volume create rocketchat-uploads
docker volume create taiga-media-data
docker volume create taiga-static-data
docker volume create wikijs-content
