version: '3.8'

services:

  # RedisInsight
  # https://docs.redislabs.com/latest/ri/installing/install-docker/
  # https://tech.guitarrapc.com/entry/2019/12/13/043349
  # https://sunday-morning.app/posts/2020-09-13-redisinsight-docker
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    hostname: redisinsight-server
    environment:
      # for nginx-proxy
      - VIRTUAL_HOST=redis.<DOMAIN>
      - VIRTUAL_PORT=8001
      - NETWORK_ACCESS=internal

      - TZ=<TZ>
    expose:
      - '8001'
    volumes:
      - redisinsight-data:/db
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: unless-stopped
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - api.segment.io:192.0.2.0

volumes:
  redisinsight-data:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
