version: '3.8'

services:

  # Redis
  # https://hub.docker.com/_/redis
  redis:
    image: redis:6-alpine
    container_name: redis
    hostname: redis-server
    environment:
      - TZ=<TZ>
    expose:
      - '6379'
    volumes:
      - redis-data:/data
      # tzdata
      - /usr/share/zoneinfo/<TZ>:/usr/share/zoneinfo/<TZ>:ro
    restart: always
    networks:
      - container-link
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:
    external: true

networks:
  default:
    external:
      name: bridge
  container-link:
    name: docker.internal
